name: Build and Deploy
on:
  push:
    branches:
      - 'dev'
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install and Build 🔧
        env:
          CNAME_URL: ${{ secrets.CNAME_URL }}
        run: |
          npm ci
          npm run build
          cp CNAME dist/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: master # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          single-commit: true
